---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::cutadapt=5.2 # matching https://github.com/nf-core/modules/blob/master/modules/nf-core/cutadapt/main.nf